/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'regan.johnson' at '17/10/16 7:37 PM' with Gradle 2.14.1
 *
 * @author regan.johnson, @date 17/10/16 7:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
